///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String mainLogo = 'assets/images/1k.png';
  static const String googleLogo = 'assets/images/google.png';
  static const String imagesSweatshirt = 'assets/images/sweatshirt.jpeg';
}
